import type { Course, Testimonial, BlogPost, Event, HeroSlide } from '@/types';

export const courses: Course[] = [
  {
    id: 'c1',
    title: '.NET Development (C#, ASP.NET)',
    description:
      'Master C#, ASP.NET, MVC, Web API, and SQL Server to build secure, high-performance enterprise-level applications.',
    imageUrl: '/dotnet.png',
    imageHint: 'dotnet development',
       rating: 4.7,
    reviews: 98,
    price: 45000,
    category: '.NET',
    duration : '6 Months',
    slug: 'dot-net-development',
  },
  {
    id: 'c2',
    title: 'Data Analytics',
    description:
      'Analyze data using Excel, SQL, Python, Power BI, and statistics to gain insights and make data-driven business decisions.',
    imageUrl: '/data-analytics.png',
    imageHint: 'data analytics',
    
    rating: 4.9,
    reviews: 180,
    price: 65000,
    category: 'Data Analytics',
      duration : '6 Months',
      slug: 'data-analytics',

  },
  {
  id: 'c3',
  title: 'Data Science',
  description:
    'Analyze data using Excel, SQL, Python, Power BI, and statistics to gain insights and make data-driven business decisions.',
  imageUrl: '/data-science.png',
  imageHint: 'data analytics',
  rating: 4.9,
  reviews: 180,
  price: 75000,
  category: 'Data Science',
    duration : '6 Months',
    slug: 'data-science',
},
    {
    id: 'c4',
    title: 'Salesforce Development',

    description:
      'Learn Salesforce fundamentals, Apex, Lightning Web Components, and integrations to build powerful CRM solutions.',
    imageUrl: '/salesforce.png',
    imageHint: 'salesforce development',
    rating: 4.7,
    reviews: 95,
    price: 45000,
    category: 'Salesforce',
      duration : '6 Months',
      slug: 'salesforce-development',
  },
{
  id: 'c5',
  title: 'Project Manager (Project Planning, Execution & Delivery)',
  description:
    'Learn project management fundamentals including planning, execution, monitoring, risk management, and delivery.',
  imageUrl: '/project-management.png',
  imageHint: 'project management',
  rating: 4.6,
  reviews: 130,
  price: 45000,
  category: 'Management',
    duration : '6 Months',
    slug: 'project-manager',
},
{
  id: 'c6',
  title: 'Ethical Hacking',
  description:
    'Understand cybersecurity concepts, ethical hacking techniques, penetration testing, and network security.',
  imageUrl: '/Ethical-Hacking .png',
  imageHint: 'ethical hacking',
  rating: 4.8,
  reviews: 220,
  price: 45000,
  category: 'Ethical Hacking',
    duration : '6 Months',
    slug: 'ethical-hacking',
},
{
  id: 'c7',
  title: 'Software Testing',
  description:
    'Learn manual testing, automation testing, Selenium, test case design, and QA processes for software projects.',
  imageUrl: '/Software Testing.png',
  imageHint: 'software testing',
  rating: 4.5,
  reviews: 115,
  price: 45000,
  category: 'Testing',
    duration : '6 Months',
    slug: 'software-testing',
},
{
  id: 'c8',
  title: 'UI / UX Design',
  description:
    'Learn user interface and user experience design principles, wireframing, prototyping, usability testing, and modern design tools.',
  imageUrl: '/ui-ux1.png',
  imageHint: 'ui ux design',
  rating: 4.7,
  reviews: 140,
  price: 45000,
  category: 'UI/UX',
    duration : '6 Months',
    slug: 'ui-ux-design',
},
{
  id: 'c9',
  title: 'API & Automation Testing',
  description:
    'Master API testing, automation frameworks, REST APIs, Postman, Selenium, and automated testing best practices.',
  imageUrl: '/api-automation-testing.png',
  imageHint: 'automation testing',
  rating: 4.8,
  reviews: 165,
  price: 45000,
  category: 'Testing',
    duration : '6 Months',
    slug: 'api-automation-testing',
},
{
  id: 'c10',
  title: 'ChatGPT for Scrum Masters (AI in Agile & Scrum Practices)',
  description:
    'Learn how to use ChatGPT and AI tools to improve Agile planning, sprint management, retrospectives, and Scrum ceremonies.',
  imageUrl: '/chatgpt-scrum.png',
  imageHint: 'agile scrum ai',
  rating: 4.6,
  reviews: 90,
  price: 45000,
  category: 'Management',
    duration : '6 Months',
    slug: 'chatgpt-for-scrum-masters',
},
{
  id: 'c11',
  title: 'Game Development (2D & 3D Games)',
  description:
    'Build 2D and 3D games using game engines, logic, physics, and animations. Learn game design concepts and mechanics.',
  imageUrl: '/game-development.png',
  imageHint: 'game development',
  rating: 4.8,
  reviews: 175,
  price: 45000,
  category: 'Game Development',
    duration : '6 Months',
    slug: 'game-development',
},
{
  id: 'c12',
  title: 'Machine Learning',
  description:
    'Understand machine learning concepts, algorithms, supervised and unsupervised learning, and real-world ML applications.',
  imageUrl: '/machine-learning.png',
  imageHint: 'machine learning',
  rating: 4.9,
  reviews: 230,
  price: 75000,
  category: 'Artificial Intelligence',
    duration : '6 Months',
    slug: 'machine-learning',
},
{
  id: 'c13',
  title: 'Artificial Intelligence',
  description:
    'Learn artificial intelligence fundamentals including neural networks, deep learning, NLP, and AI-driven solutions.',
  imageUrl: '/artificial-intelligence.png',
  imageHint: 'artificial intelligence',
  rating: 4.9,
  reviews: 260,
  price: 75000,
  category: 'Artificial Intelligence',
    duration : '6 Months',
    slug: 'artificial-intelligence',
},
{
  id: 'c14',
  title: 'Digital Marketing (SEO, Social Media, Paid Ads & Analytics)',
  description:
    'Master digital marketing strategies including SEO, social media marketing, paid advertising, Google Analytics, and branding.',
  imageUrl: '/digital-marketing.png',
  imageHint: 'digital marketing',
  rating: 4.6,
  reviews: 150,
  price: 45000,
  category: 'Marketing',
    duration : '6 Months',
    slug: 'digital-marketing',
},
{
  id: 'c15',
  title: 'Network Security',
  description:
    'Learn network security concepts, firewalls, encryption, threat detection, and securing enterprise networks.',
  imageUrl: '/network-security.png',
  imageHint: 'network security',
  rating: 4.7,
  reviews: 135,
  price: 45000,
  category: 'Cyber Security',
    duration : '6 Months',
    slug: 'network-security',
},
{
  id: 'c16',
  title: 'Back-End Development',
  description:
    'Learn backend development concepts including server-side programming, databases, APIs, authentication, and deployment.',
  imageUrl: '/full-stack1.png',
  imageHint: 'backend development',
  rating: 4.7,
  reviews: 145,
  price: 45000,
  category: 'Backend',
    duration : '6 Months',
    slug: 'backend-development',
},
{
  id: 'c17',
  title: 'C Programming Language',
  description:
    'Master the fundamentals of C programming including variables, loops, functions, pointers, memory management, and file handling.',
  imageUrl: '/c-language.png',
  imageHint: 'c programming',
  rating: 4.6,
  reviews: 120,
  price: 45000,
  category: 'Programming',
    duration : '6 Months',
    slug: 'c-programming-language',
},
{
  id: 'c18',
  title: 'C++ Programming Language',
  description:
    'Learn object-oriented programming with C++, covering classes, inheritance, polymorphism, STL, and real-world problem solving.',
  imageUrl: '/c++.png',
  imageHint: 'c plus plus',
  rating: 4.7,
  reviews: 135,
  price: 45000,
  category: 'Programming',
    duration : '6 Months',
    slug: 'cpp-language',
},
{
  id: 'c19',
  title: 'Cloud Computing (AWS & Azure)',
  description:
    'Understand cloud computing concepts and gain hands-on experience with AWS and Azure services, deployment, and cloud security.',
  imageUrl: '/Cloud Computing.png',
  imageHint: 'cloud computing',
  rating: 4.8,
  reviews: 190,
  price: 45000,
  category: 'Cloud',
    duration : '6 Months',
    slug: 'cloud-computing',
},
{
  id: 'c20',
  title: 'Data Architecture',
  description:
    'Learn data modeling, data warehousing, ETL pipelines, and designing scalable data architectures for enterprise systems.',
  imageUrl: '/data-science.png',
  imageHint: 'data architecture',
  rating: 4.7,
  reviews: 125,
  price: 65000,
  category: 'Data Engineering',
    duration : '6 Months',
    slug: 'data-architecture',
},
{
  id: 'c21',
  title: 'Flutter Development',
  description:
    'Build cross-platform mobile applications using Flutter and Dart with modern UI, APIs, and real-world projects.',
  imageUrl: '/flutter.png',
  imageHint: 'flutter development',
  rating: 4.8,
  reviews: 175,
  price: 45000,
  category: 'Mobile Development',
    duration : '6 Months',
    slug: 'flutter-development',
},
{
  id: 'c22',
  title: 'Front-End Development',
  description:
    'Learn HTML, CSS, JavaScript, responsive design, and modern frontend frameworks to build interactive web interfaces.',
  imageUrl: '/frontend-development.png',
  imageHint: 'frontend development',
  rating: 4.7,
  reviews: 160,
  price: 45000,
  category: 'Frontend',
    duration : '6 Months',
    slug: 'front-end-development',
},
{
  id: 'c23',
  title: 'Full Stack Web Development',
  description:
    'Become a full-stack developer by mastering HTML, CSS, JavaScript, React, databases, and backend technologies.',
  imageUrl: '/full-stack3.png',
  imageHint: 'full stack development',
  rating: 4.9,
  reviews: 220,
  price: 45000,
  category: 'Full Stack',
    duration : '6 Months',
    slug: 'full-stack-web-development',
},
{
  id: 'c24',
  title: 'iOS Development (Swift & Apple Ecosystem Apps)',
  description:
    'Learn iOS app development using Swift, Xcode, and Apple frameworks to build high-quality iPhone and iPad applications.',
  imageUrl: '/ios-development.png',
  imageHint: 'ios swift development',
  rating: 4.8,
  reviews: 160,
  price: 45000,
  category: 'Mobile Development',
    duration : '6 Months',
    slug: 'ios-development',
},
{
  id: 'c25',
  title: 'Java Full Stack Development (Core Java, Spring Boot & Enterprise Apps)',
  description:
    'Become a Java full-stack developer by mastering Core Java, Spring Boot, REST APIs, databases, and enterprise application development.',
  imageUrl: '/java-full.png',
  imageHint: 'java full stack',
  rating: 4.9,
  reviews: 210,
  price: 45000,
  category: 'Full Stack',
    duration : '6 Months',
    slug: 'java-full-stack-development',
},
{
  id: 'c26',
  title: 'Java Programming (Core Java & OOP Concepts)',
  description:
    'Learn Core Java programming including OOP principles, exception handling, collections, multithreading, and best practices.',
  imageUrl: '/corejava.png',
  imageHint: 'java programming',
  rating: 4.7,
  reviews: 170,
  price: 45000,
  category: 'Programming',
    duration : '6 Months',
    slug: 'java-programming',
},
{
  id: 'c27',
  title: 'Kotlin Development',
  description:
    'Build modern Android applications using Kotlin, covering language fundamentals, Android components, and app architecture.',
  imageUrl: '/kotlin.png',
  imageHint: 'kotlin development',
  rating: 4.8,
  reviews: 150,
  price: 45000,
  category: 'Mobile Development',
    duration : '6 Months',
    slug: 'kotlin-development',
},
{
  id: 'c28',
  title: 'MERN Stack Development (MongoDB, Express, React, Node.js)',
  description:
    'Become a full-stack JavaScript developer by mastering MongoDB, Express, React, and Node.js with hands-on projects.',
  imageUrl: '/full-stack1.png',
  imageHint: 'mern stack',
  rating: 4.8,
  reviews: 210,
  price: 45000,
  category: 'Full Stack',
    duration : '6 Months',
    slug: 'mern-stack-development',
},

{
  id: 'c29',
  title: 'Mobile App Development (Android & iOS)',
  description:
    'Develop mobile applications for Android and iOS platforms using modern tools, frameworks, and best practices.',
  imageUrl: '/app.png',
  imageHint: 'mobile app development',
  rating: 4.8,
  reviews: 190,
  price: 45000,
  category: 'Mobile Development',
    duration : '6 Months',
    slug: 'mobile-app-development',
},
{
  id: 'c30',
  title: 'PHP Web Development (Core PHP, MySQL & Web Applications)',
  description:
    'Learn Core PHP, MySQL, and web application development to build dynamic, database-driven websites.',
  imageUrl: '/php.png',
  imageHint: 'php web development',
  rating: 4.6,
  reviews: 140,
  price: 45000,
  category: 'Backend',
    duration : '6 Months',
    slug: 'php-web-development',
},
{
  id: 'c31',
  title: 'Power BI',
  description:
    'Learn Power BI for data visualization, dashboards, reports, and business intelligence using real-world datasets.',
  imageUrl: '/power-bi.png',
  imageHint: 'power bi',
  rating: 4.7,
  reviews: 145,
  price: 65000,
  category: 'Data Analytics',
    duration : '6 Months',
    slug: 'power-bi',
},

{
  id: 'c32',
  title: ' Python Full Stack Development (Backend, Automation & APIs)',
  description:
    'Learn Core Python programming, automation scripting, file handling, OOP concepts, and real-world use cases.',
  imageUrl: '/python.png',
  imageHint: 'python programming',
  rating: 4.7,
  reviews: 170,
  price: 45000,
  category: 'Programming',
    duration : '6 Months',
    slug: 'python-full-stack',
},
{
  id: 'c33',
  title: 'React Development',
  description:
    'Build modern, responsive web applications using React, hooks, component architecture, and best practices.',
  imageUrl: '/react.png',
  imageHint: 'react development',
  rating: 4.9,
  reviews: 230,
  price: 45000,
  category: 'Frontend',
    duration : '6 Months',
    slug: 'react-development',
},
{
  id: 'c34',
  title: 'React Native Development (Android Apps with JavaScript)',
  description:
    'Develop cross-platform mobile applications using React Native and JavaScript for Android and iOS.',
  imageUrl: '/native.png',
  imageHint: 'react native',
  rating: 4.8,
  reviews: 185,
  price: 45000,
  category: 'Mobile Development',
    duration : '6 Months',
    slug: 'react-native-development',
},
{
  id: 'c35',
  title: 'Rust Programming Language',
  description:
    'Learn Rust programming for performance, safety, and concurrency. Ideal for system-level and backend development.',
  imageUrl: '/rust.png',
  imageHint: 'rust programming',
  rating: 4.6,
  reviews: 120,
  price: 45000,
  category: 'Programming',
    duration : '6 Months',
    slug: 'rust-programming',
},
{
  id: 'c36',
  title: 'SQL for Data Science',
  description:
    'Learn SQL queries, joins, subqueries, and data analysis techniques used in data science and analytics roles.',
  imageUrl: '/sql-data-science.png',
  imageHint: 'sql data science',
  rating: 4.8,
  reviews: 160,
  price: 75000,
  category: 'Data Science',
    duration : '6 Months',
    slug: 'sql-for-data-science',
},
{
  id: 'c37',
  title: 'Tableau (Data Visualization & Dashboard Creation)',
  description:
    'Master Tableau for creating interactive dashboards, visual analytics, and data-driven business insights.',
  imageUrl: '/table.png',
  imageHint: 'tableau dashboards',
  rating: 4.7,
  reviews: 150,
  price: 65000,
  category: 'Data Analytics',
    duration : '6 Months',
    slug: 'tableau',
},
{
  id: 'c38',
  title: 'WordPress Development',
  description:
    'Learn WordPress development including themes, plugins, customization, SEO, and building professional websites.',
  imageUrl: '/wordpress.png',
  imageHint: 'wordpress development',
  rating: 4.6,
  reviews: 140,
  price: 45000,
  category: 'Web Development',
    duration : '6 Months',
    slug: 'wordpress-development',
},
{
  id: 'c39',
  title: 'Generative AI',
  description:'Learn to build and deploy generative AI applications using large language models, prompt engineering, and RAG pipelines.',
  imageUrl: '/generative-ai.png',
  imageHint: 'generative ai',
  rating: 4.6,
  reviews: 140,
  price: 45000,
  category: 'AI & Machine Learning',
    duration : '6 Months',
    slug: 'generative-ai',
},

{
  id: 'c40',
  title: 'NLP with Deep Learning',
  description:'Learn to build and deploy NLP applications using deep learning models like transformers, BERT, and GPT.',
  imageUrl: '/nlp-with-deep-learning.png',
  imageHint: 'nlp deep learning',
  rating: 4.6,
  reviews: 140,
  price: 45000,
  category: 'AI & Machine Learning',
  duration : '6 Months',
  slug: 'nlp-with-deep-learning',
},


{
  id: 'c41',
  title: 'Python Programming Language (Core Python & Automation)',
  description:'Learn core Python programming concepts and automation techniques for real-world applications.',
  imageUrl: '/python-core.png',
  imageHint: 'python programming',
  rating: 4.6,
  reviews: 140,
  price: 45000,
  category: 'Programming',
  duration : '6 Months',
  slug: 'python-programming',
},

];


export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Rupali Gaikwad',
    course: 'Full Stack Web Development',
    quote: 'Paarsh E-learning changed my life. The one-to-one mentorship was a game-changer, and I landed my dream job within a month of completing the course!',
    imageUrl: '/user.png',
    imageHint: 'person smiling'
  },
  {
    id: 't2',
    name: 'Harshda Ahire',
    course: 'Data Analyst',
    quote: 'The instructors are industry experts who provide invaluable insights. The placement support is top-notch. Highly recommended!',
    imageUrl: '/user.png',
    imageHint: 'person portrait'
  },
  {
    id: 't3',
    name: 'Shivani Deshmukh',
    course: 'Flutter Developer',
    quote: 'I went from a complete beginner to a confident designer. The hands-on projects and portfolio reviews were incredibly helpful.',
    imageUrl: '/user.png',
    imageHint: 'professional person'
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'b1',
    title: 'Roadmap to Become a Full Stack Developer in 2024',
    excerpt:
      'Learn the step-by-step roadmap to becoming a full stack developer, including frontend, backend, databases, and real-world project skills.',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    imageHint: 'full stack web development coding',
    author: 'Admin',
    date: '2024-07-20',
  },
  {
    id: 'b2',
    title: 'Data Science vs Machine Learning: What Should You Learn First?',
    excerpt:
      'Confused between data science and machine learning? This guide explains the differences, career paths, and which skill to start with.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    imageHint: 'data science analytics dashboard',
    author: 'Admin',
    date: '2024-07-18',
  },
  {
    id: 'b3',
    title: 'UI/UX Design Fundamentals Every Beginner Must Know',
    excerpt:
      'Discover the core principles of UI/UX design, including user research, wireframing, usability, and creating intuitive interfaces.',
    imageUrl: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=800&q=80',
    imageHint: 'ui ux design wireframe workspace',
    author: 'Admin',
    date: '2024-07-15',
  },
];


   export const events: Event[] = [
    {
        id: 'e1',
        title: 'Live Q&A with a Google Recruiter',
        type: 'Webinar',
        date: 'August 5, 2024',
    },
    {
        id: 'e2',
        title: 'Portfolio Review Workshop',
        type: 'Workshop',
        date: 'August 12, 2024',
    },
    {
        id: 'e3',
        title: 'Mastering React Hooks',
        type: 'Webinar',
        date: 'August 19, 2024',
    },
]

export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    title: 'Transform Your Career with Personalized Tech Education',
    subtitle: 'One-to-one mentorship, limited seats, and a curriculum designed for your success. Your dream job is closer than you think.',
    imageUrl: '/banner2.png',
    imageHint: 'student laptop',
    alt: 'Student learning on a laptop',
  },
  {
    id: 2,
    title: 'Placement-Oriented Learning for Ambitious Minds',
    subtitle: 'We bridge the gap between education and industry with structured interview opportunities and real-world projects.',
    imageUrl: '/banner3.png',
    imageHint: 'developer coding',
    alt: 'Developer coding at a desk',
  },
  // {
  //   id: 3,
  //   title: 'Join an Exclusive Community of Learners',
  //   subtitle: 'With limited seats per month, you get the focused attention you need to excel and build lasting connections.',
  //   imageUrl: 'https://picsum.photos/seed/hero3/1920/1080',
  //   imageHint: 'students collaborating',
  //   alt: 'Students collaborating in a modern workspace',
  // }
];

export const users = [
  {
    id: 'usr_1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'Student',
    status: 'Active',
    joined: '2023-01-15',
  },
  {
    id: 'usr_2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'Teacher',
    status: 'Active',
    joined: '2022-11-20',
  },
  {
    id: 'usr_3',
    name: 'Admin User',
    email: 'admin@eduleap.com',
    role: 'Admin',
    status: 'Active',
    joined: '2022-10-01',
  },
   {
    id: 'usr_4',
    name: 'Emily White',
    email: 'emily.white@example.com',
    role: 'Student',
    status: 'Inactive',
    joined: '2023-03-10',
  },
   {
    id: 'usr_5',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    role: 'Student',
    status: 'Active',
    joined: '2023-05-22',
  },
];